
# Deployment options
contourhelm:
  enabled: false  
gatewayprovisioner:
  enabled: true
  dynamic: 
    enabled: true

istiohelm:
  enabled: true

# common stuff
ingress:
  domain: example.com
  domains: # TODO:remove!
    - example.com

certManager:
  namespace: cert-manager

loadbalancer:
  http:
    port: 80
  https:
    port: 443
  tls:
    port: 8443

test:
  enabled: true

  image: ghcr.io/gernoteger/contour-test

# only used with helm deployment!

istiod:
  # enable TLSRoute, TCPRoute
  # https://github.com/istio/istio/discussions/48807#discussioncomment-8372247
  pilot:
    env:
      # see: https://istio.io/latest/docs/reference/commands/pilot-discovery/
      PILOT_ENABLE_ALPHA_GATEWAY_API: true # enable TLSRoute

# TODO: put elsewhere or own namespace of operator
kiali-operator: # https://kiali.io/docs/installation/installation-guide/install-with-helm/
  cr:
    create: true
    namespace: istio-system
    spec:
      auth:
        strategy: anonymous
