
# Deployment options
contourhelm:
  enabled: false  
gatewayprovisioner:
  enabled: true
  dynamic: 
    enabled: true

istiohelm:
  enabled: false

# common stuff
ingress:
  domain: example.com
  domains: # TODO:remove!
    - example.com

certManager:
  namespace: cert-manager

loadbalancer:
  http:
    port: 80
  https:
    port: 443
  tls:
    port: 8443

test:
  enabled: true

  image: ghcr.io/gernoteger/contour-test

# only used with helm deployment!

#istio: # the helm chart..