# our self-signed ca
#TODO: where does this belong??

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Values.certManager.namespace}}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
  namespace: {{ .Values.certManager.namespace}}
spec:
  isCA: true
  commonName: cluster-ca
  subject:
    organizations:
      - Gernot
    organizationalUnits:
      - Me
  secretName: cluster-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

