
# see: https://cert-manager.io/docs/usage/certificate/
# https://cert-manager.io/docs/devops-tips/syncing-secrets-across-namespaces/

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  default-tls-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName:  default-tls-cert
 
  duration: 240h
  renewBefore: 200h


  usages:
    - server auth
  #  - client auth
  # At least one of a DNS Name, URI, IP address or otherName is required.
  dnsNames:
{{- range $domain:=.Values.ingress.domains }}
    - "*.{{ $domain }}"
{{- end }}
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer

