
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: default-edge
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.loadbalancer.http.port }}
      allowedRoutes:
        namespaces:
          from: All
    - name: tls 
      protocol: TLS
      port: {{ .Values.loadbalancer.https.port }}

      tls:
        mode: Passthrough # If protocol is `TLS`, `Passthrough` is a possible mode

      allowedRoutes:
        namespaces:
          from: All

    - name: legacy # match Ingress and HTTPProxy, This works ONLY with contour!
      # https://projectcontour.io/docs/1.29/config/gateway-api/#routing-with-httpproxy-or-ingress
      protocol: projectcontour.io/https # not working here!
      port: {{ .Values.loadbalancer.https.port }}

      allowedRoutes:
        namespaces:
          from: All