
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: default-edge
  #gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.loadbalancer.http.port }}
      allowedRoutes:
        namespaces:
          from: All
    - name: tls 
      protocol: TLS
      port: {{ .Values.loadbalancer.https.port }}

      tls:
        mode: Passthrough # If protocol is `TLS`, `Passthrough` is a possible mode

      allowedRoutes:
        namespaces:
          from: All

 