
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: internal
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: default-internal
  listeners:
    - name: https
      protocol: HTTPS
      port: {{ .Values.loadbalancer.https.port }}

      tls:
        mode: Terminate # If protocol is `TLS`, `Passthrough` is a possible mode
        certificateRefs:
        - kind: Secret
          group: ""
          name: default-tls-cert

      allowedRoutes:
        namespaces:
          from: All
