# Ingress by Gateway API

---
#https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1alpha2.TLSRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: edge2internal
  namespace: {{ .Release.Namespace }}
  # Description: gateway to edge->internal

spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: edge
    namespace: projectcontour

  hostnames:
{{- range $domain:=.Values.ingress.domains }}
  - "*.{{ $domain }}"
{{- end }}
  rules:
  - backendRefs: 
    - name: envoy-internal 
      kind: Service
      port: 443

    # not allowed!! Could be enhancement!!
    # - name: envoy-internal 
    #   group: gateway.networking.k8s.io
    #   kind: Gateway
    #   port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: internal2contour-legacy
  namespace: {{ .Release.Namespace }}
  # Description: gateway to internal->legacy

spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: internal # upstream gateway
    namespace: projectcontour

  hostnames:
{{- range $domain:=.Values.ingress.domains }}
  - "*.{{ $domain }}"
{{- end }}
  rules:
  - backendRefs: 
    - name: envoy-contour-legacy # donstream gateway
      kind: Service
      port: 443
