
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: internal
  namespace: {{ .Release.Namespace }}
  # https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/
  # https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment
  annotations:
    networking.istio.io/service-type: ClusterIP
spec:
  gatewayClassName: default-internal
  listeners:
    - name: https
      
      protocol: HTTPS
      port: {{ .Values.loadbalancer.https.port }}

      tls:
        mode: Terminate # If protocol is `TLS`, `Passthrough` is a possible mode
        certificateRefs:
        - kind: Secret
          group: ""
          name: default-tls-cert

      allowedRoutes:
        namespaces:
          from: All

    #NEEDS router
    # - name: legacy # TOD: can this be in edge?
    #   # https://projectcontour.io/docs/1.29/config/gateway-api/#routing-with-httpproxy-or-ingress
    #   protocol: projectcontour.io/https # not working here!
    #   port: {{ .Values.loadbalancer.https.port }}

    #   allowedRoutes:
    #     namespaces:
    #       from: All
