apiVersion: v2
name: contour
description: contour gateway-provosioner

type: application

version: 0.1.0

appVersion: "1.29.1" 

dependencies: 
  - name: contour
    # https://artifacthub.io/packages/helm/bitnami/contour
    # https://github.com/bitnami/charts/tree/main/bitnami/contour

    version: "18.2.9"
    repository: https://charts.bitnami.com/bitnami
    #repository: oci://registry-1.docker.io/bitnamicharts/contour
    condition: contourhelm.enabled


# https://projectcontour.io/getting-started/#option-2-helm