test:
  enabled: true

  image: ghcr.io/gernoteger/contour-test

contourhelm:
  enabled: true
  
gatewayprovisioner:
  enabled: false
  dynamic: 
    enabled: false

ingress:
  domains:
    #- projectcontour.io # fixed for hardwired tests
    - example.com

certManager:
  namespace: cert-manager

loadbalancer:
  http:
    port: 80
  https:
    port: 443
  tls:
    port: 8443

contour:
  contour:
    manageCRDs: false
  configInline:
    tls:
      #   minimum TLS version that Contour will negotiate
      #   minimum-protocol-version: "1.1"
      # Defines the Kubernetes name/namespace matching a secret to use
      # as the fallback certificate when requests which don't match the
      # SNI defined for a vhost.
      fallback-certificate:
        name: default-tls-cert
        namespace: projectcontour # required!!
    #   name: fallback-secret-name
    #   namespace: projectcontour