test:
  enabled: true

  image: ghcr.io/gernoteger/contour-test

contourhelm:
  enabled: true
  
gatewayprovisioner:
  enabled: false
  dynamic: 
    enabled: false

ingress:
  domains:
    #- projectcontour.io # fixed for hardwired tests
    - example.com

certManager:
  namespace: cert-manager

loadbalancer:
  http:
    port: 80
  https:
    port: 443
  tls:
    port: 8443

contour:
  contour:
    manageCRDs: false
    # image: #https://hub.docker.com/r/bitnami/contour
    #   # tag: 1.29.1-debian-12-r3
    #   #tag: 1.28

  configInline:
    tls:
      #   minimum TLS version that Contour will negotiate
      #   minimum-protocol-version: "1.1"
      # Defines the Kubernetes name/namespace matching a secret to use
      # as the fallback certificate when requests which don't match the
      # SNI defined for a vhost.
      fallback-certificate:
        name: default-tls-cert
        namespace: projectcontour # required!!
    #   name: fallback-secret-name
    #   namespace: projectcontour
  
  envoy:
    logLevel: info # info warning
    extraArgs:
    - "--component-log-level" # https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-component-log-level
    - "conn_handler:debug,connection:info"
    image:
      tag: 1.30.4-debian-12-r1 # https://hub.docker.com/r/bitnami/envoy/tags
      #tag: 1.28