test:
  enabled: true

  image: ghcr.io/gernoteger/contour-test


gatewayprovisioner:
  enabled: true
  dynamic: 
    enabled: false

ingress:
  domains:
    - example.com

certManager:
  namespace: cert-manager

loadbalancer:
  http:
    port: 80
  https:
    port: 443
  tls:
    port: 8443