# Ingress by Gateway API
{{ if .Values.test.enabled }}
{{ if .Values.workload.gatewayapi.enabled }}
---
#https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1alpha2.TLSRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: echo-tls
  namespace: {{ .Release.Namespace }}

spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: edge
    namespace: {{ include "gateways.namespace" . }}
  hostnames:
{{- range $domain:=.Values.ingress.domains }}
  - "echo-tls.{{ $domain }}"
{{- end }}
  rules:
  - backendRefs: 
    - name: echo 
      kind: Service
      port: 443

{{ end }}
{{ end }}