# Ingress by Gateway API
{{ if .Values.test.enabled }}
{{ if .Values.workload.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-http
  namespace: {{ .Release.Namespace }}

spec:
  rules:
{{- range $domain:=.Values.ingress.domains }}
  - host: "echo-ingress-http.{{ $domain }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo
            port:
              number: 80
{{ end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-https
  namespace: {{ .Release.Namespace }}

spec:
  tls:
{{- range $domain:=.Values.ingress.domains }}
  - hosts:
      - "echo-ingress-https.{{ $domain }}"
{{ end }}
    secretName: echo-ingress-cert # default-tls-cert
  rules:
{{- range $domain:=.Values.ingress.domains }}
  - host: "echo-ingress-https.{{ $domain }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo
            port:
              number: 80
{{ end }}

{{ end }}
{{ end }}